apiVersion: v1
kind: Pod
metadata:
  name: mongo-restore
  namespace: ferretdb
spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
  containers:
    - name: mongo-restore
      image: mongo:6.0
      command: [ "sleep", "infinity" ]   # Keeps the pod alive for file transfer & restore
