apiVersion: v1
kind: Pod
metadata:
  name: mongo-dump
spec:
  restartPolicy: Never
  #nodeSelector:
    #kubernetes.io/os: linux
    #kubernetes.io/arch: amd64
  containers:
    - name: mongo-dump
      image: mongo:5
      command: ["/bin/sh", "-c"]
      args:
        - |
          mongodump --uri="mongodb://<user>:<password>@<host>:27017/" --out=/dump &&
          echo "Dump Completed Successfully!" &&
          sleep infinity
      volumeMounts:
        - name: dump-volume
          mountPath: /dump
  volumes:
    - name: dump-volume
      emptyDir: {}

