apiVersion: v1
kind: Pod
metadata:
  name: mongo-restore
  namespace: {{ .Values.restore.namespace }}
spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
  containers:
    - name: mongo-restore
      image: mongo:6.0
      command: [ "sleep", "infinity" ]
