apiVersion: v1
kind: Pod
metadata:
  name: mongo-dump
spec:
  restartPolicy: Never
  containers:
    - name: mongo-dump
      image: mongo:6.0
      command: ["/bin/sh", "-c"]
      args:
        - |
          mongodump --uri="{{ .Values.source.uri }}" --out=/dump &&
          echo "Dump Completed Successfully!" &&
          sleep infinity
      volumeMounts:
        - name: dump-volume
          mountPath: /dump
  volumes:
    - name: dump-volume
      emptyDir: {}
